let someCondition = true;

try {

} catch (exception) {
    throw new Error("something wrong 333")
}